Display real json data from xdr
tupui/soroban-versioning pull request #115
Opened 2024-12-13 14:47 UTC by 0xExp-po

2024-12-14 17:30 UTC, tupui requested changes
Looks good, just some cleanup I believe

2024-12-14 17:30 UTC, tupui commented on AES256-encryptor/.gitignore
I think we can delete the whole folder now.

2024-12-14 17:30 UTC, tupui commented on dapp/src/utils/stellarXdr.ts
> +    console.log("Stellar XDR JSON initialized");
I think we can cleanup all log

2024-12-14 17:30 UTC, tupui commented on dapp/src/utils/stellarXdr.ts
Why is this needed? Please add a comment

2024-12-15 00:35 UTC, 0xExp-po commented on dapp/src/utils/stellarXdr.ts
stellar-xdr-json module is the best module to convert xdr to json data.
but this module is built with rust and we need initialize the module wasm to use this module.
So this initialize function is required and I added this

2024-12-16 09:09 UTC, tupui approved these changes

2024-12-16 09:10 UTC, merged